import { Geist, Geist_Mono } from "next/font/google";
import dynamic from "next/dynamic";
import "./globals.css";
import Header from "@/components/Header";

const Footer = dynamic(() => import("@/components/Footer"), { ssr: true });
const CookieBanner = dynamic(() => import("@/components/CookieBanner"), { ssr: true });
const AnalyticsLoader = dynamic(() => import("@/components/AnalyticsLoader"), { ssr: true });
const AccessibilityWidget = dynamic(() => import("@/components/AccessibilityWidget"), { ssr: true });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "The-Realtor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Header />

        <main>{children}</main>

        <Footer />

        {/* Global UI & logic */}
        <CookieBanner />
         <AnalyticsLoader />
        <AccessibilityWidget />     
      </body>
    </html>
  );
}
