import { Geist, Geist_Mono } from "next/font/google";
import dynamic from "next/dynamic";
import "./globals.css";
import Header from "@/components/Header";
import ConditionalFooter from "@/components/ConditionalFooter";

const CookieBanner = dynamic(() => import("@/components/CookieBanner"), { ssr: true });
const AnalyticsLoader = dynamic(() => import("@/components/AnalyticsLoader"), { ssr: true });
const AccessibilityWidget = dynamic(() => import("@/components/AccessibilityWidget"), { ssr: true });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "The-Realtor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        suppressHydrationWarning
      >
        <Header />

        <main className="flex-1">{children}</main>

        {/* Footer - conditionally hidden on listings page */}
        <ConditionalFooter />

        {/* Global UI & logic */}
        <CookieBanner />
         <AnalyticsLoader />
        <AccessibilityWidget />     
      </body>
    </html>
  );
}
